sudo: required
services:
- docker
os:
- linux
language:
- generic
install:
- sudo apt-get install -y debootstrap binfmt-support qemu-user-static
script:
- cd $TRAVIS_BUILD_DIR/$TC && sudo ./bootstrap.sh
after_success:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- export REPO=alxchk/docker-old-tc-bootstrap
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- cd $TRAVIS_BUILD_DIR/$TC && docker tag $TC alxchk/$TC:$TAG
- cd $TRAVIS_BUILD_DIR/$TC && docker push alxchk/$TC:$TAG >/dev/null && echo "Pushed alxchk/$TC:$TAG"
env:
  matrix:
  - TC=linux-armhf
  - TC=linux32
  - TC=linux64
